# Generated by Django 5.2.2 on 2025-06-29 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medidash', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='serial_number',
            new_name='MAC_Address',
        ),
    ]
