# Generated by Django 5.2.2 on 2025-06-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medidash', '0003_rename_serial_number_device_mac_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='MAC_Address',
            new_name='mac_address',
        ),
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='notification_enabled',
            new_name='email_notifications_enabled',
        ),
        migrations.RenameField(
            model_name='patientprofile',
            old_name='notification_enabled',
            new_name='email_notifications_enabled',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='profile_picture_url',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='profile_picture_url',
        ),
        migrations.AddField(
            model_name='device',
            name='device_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='device_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='device_name',
            field=models.CharField(default='Unnamed Device', max_length=100),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/doctors/'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='push_notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='sms_notifications_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=50),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='two_factor_authentication_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/patients/'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='push_notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='sms_notifications_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=50),
        ),
    ]
