# Generated by Django 4.2.7 on 2025-06-30 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medidash', '0006_customuser_middle_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='receiver',
            new_name='recipient',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='body',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='message',
            name='subject',
        ),
    ]
