# Generated by Django 4.2.7 on 2025-07-02 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medidash', '0007_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='medidash.doctorprofile'),
        ),
    ]
